spring:
  config:
    activate:
      on-profile:
        - local
        - test

  data:
    redis:
      host: localhost
      port: 6379

---

spring:
  config:
    activate:
      on-profile:
        - dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_SECRET}