spring:
  config:
    activate:
      on-profile:
        - local
        - test

  data:
    redis:
      host: localhost
      port: 6379

---

spring:
  config:
    activate:
      on-profile:
        - dev

  data:
    redis:
      host: svc.sel3.cloudtype.app
      port: 30000
      password: ${REDIS_SECRET}